config/routes.rb
Rails.application.eager_load!

Rails.application.routes.draw do

  devise_for :users

  get '/api', to: redirect('/apidocs/index.html')

  # -- Wixel

  # API
  namespace :api do
    namespace :v1 do
      resources :members, only: [:index] do
        collection do
          post 'login',                action: :login
          post 'signup',               action: :signup
          get  'is_verified',          action: :is_verified
          get  'email_exists',         action: :email_exists
          get  'refer_friends',        action: :refer_friends
          get  'force_verification',   action: :force_verification
          get  'is_paid',              action: :is_paid
          post 'upload_photo',         action: :upload_photo
          get  'profile',              action: :profile
          post 'update_profile',       action: :update_profile
        end
      end
      resources :deals, only: [:index, :show] do
        member do
          get 'toggle_favourite_deal', action: 'toggle_favourite_deal'
        end
      end
      resources :cities,       only: [:index]
      resources :universities, only: [:index]
      resources :invites,      only: [:create]
      # Members
      post 'memberships/activate',         to: 'memberships#activate'
      post 'memberships/otp_check',        to: 'memberships#activate_with_otp'
      post 'memberships/ref_code_check',   to: 'memberships#activate_with_ref_code'
    end
  end

  namespace :admin do
    resources :deals do
      put '/change-status/:status', to: 'deals#toggle_status', constraints: { status: /recommended|online|in_store|published/ }
      member do
        get 'add_branch',    action: 'add_branch'
        get 'remove_branch', action: 'remove_branch'
      end
    end
    resources :merchants do
      resources :branches, only: [:new, :edit]
    end
    resources :branches, except: [:index, :show, :new, :edit]
    resources :cities
    resources :universities
    resources :collections, only: [:index]
    resources :payments
    resources :memberships do
      member do
        get 'payment_details', action: :payment_details
      end
      collection do
        get 'set_as_paid', action: :set_as_paid, as: :bulk_paid
        get 'mail/:mail_request', action: :notify, as: :mail
        match 'report', action: :report, as: :report, via: [:get, :post]
        get 'export/:club_id', action: :export, as: :export
      end
    end
    resources :members, except: [:new] do
      member do
        put 'toggle', action: :toggle_agent
        get 'banking_panel', action: :banking_panel
      end
      collection do
        get '/new/(:id_number)', to: 'members#new', as: :new
      end
    end

    get '/exports', to: 'exports#index', as: 'exports'
    get '/exports/:id/download', to: 'exports#download', as: 'export_download'
    get '/exports/referrals', to: 'exports#referrals', as: 'export_referrals'
    get '/imports', to: 'imports#index', as: 'imports'
    post '/imports', to: 'imports#create'
    get 'imports/sample', to: 'imports#sample', as: 'imports_sample'

    # Reporting
    get 'reports/recon', to: 'reports#recon', as: 'recon_report', :defaults => {:format => :csv}
  end

  # -- /Wixel

  # Handle bank account assignment
  # -- Depreciated -- get 'referralcodes/:referral_code', to: 'memberships#refferalcode', as: 'refferalcode'
  get 'banking_details/signup/:referral_code', to: 'banking_details#new_by_referral', as: 'new_signup_banking_details'
  post 'banking_details/signup/:referral_code', to: 'banking_details#create_by_referral'
  patch 'banking_details/signup/:referral_code', to: 'banking_details#update_by_referral'

  resources :banking_details

  # -- Depreciated --  get 'clubs/:id/members', to: 'clubs#members', as: 'membership_list'
  # -- Depreciated --  get 'clubs/:id/merchants', to: 'clubs#merchants', as: 'club_merchant_list'
  get 'payments/missing', to: 'payments#missing_details', as: 'payment_missing_details'

  # -- Depreciated -- get '/memberships/club/:club_id', to: 'memberships#club', as: 'club_memberships'
  # -- Depreciated -- get '/memberships/member/:member_id', to: 'memberships#member', as: 'member_memberships'

  resources :payments do
    post 'complete' => 'payment#complete', as: 'complete'
    get  'success'  => 'payment#success',  as: 'success'
    get  'fail'     => 'payment#fail',     as: 'fail'
  end

  get 'payments/membership/:membership_id', to: 'payments#process_for_membership', as: 'payment_process_for_membership'

  resources :club_merchants
  resources :locations
  resources :merchants
  resources :members
  resources :memberships
  resources :clubs
  resources :media_contents, only: [:create]

  #get '/cards/:referral_code', to: 'cards#index', as: 'cards'
  get '/admin', to: 'admin/dashboards#index', as: 'admin_home'

  #root to: "signup#index", club_id: 1 #signup_club_path(1) #"admin/clubs#index"

  #get 'signup/club/:club_id',            to: 'signup#index',                  as: 'signup_club'
  #post 'signup/club/:club_id',           to: 'signup#create_signup_club',     as: 'signup_create_club'
  #get 'signup/referral/:referral_code',  to: 'signup#referral',               as: 'signup_referral'
  #post 'signup/referral/:referral_code', to: 'signup#create_signup_referral', as: 'signup_create_referral'
  #post 'invite_friend/:referral_code',   to: 'signup#invite_friend',          as: 'signup_invite_friend'
  #get 'signup/success_test',             to: 'signup#success_page_test',      as: 'signup_success_test'

  root to: "website#index", club_id: 1

  #--- Explicit static routing

  get  '/about',                  to: 'website#about'
  get  '/deals',                  to: 'website#index'
  get  '/welcome',                to: 'website#welcome'
  get  '/recruit',                to: 'website#recruit_earn'
  get  '/join',                   to: 'website#join'
  post '/join',                   to: 'website#do_join'
  get  '/become-a-partner',       to: 'website#become_parter'
  get  '/verify/:referral_code',  to: 'website#verify'
  post  '/verify',                to: 'website#verify'
  get  '/verified',               to: 'website#verified'
  get  '/payment/:referral_code', to: 'website#payment'
  get  '/privacy',                to: 'website#privacy'
  get  '/terms',                  to: 'website#terms'
  get  '/test-mails',             to: 'test#mailers'
  get  '/banking/:referral_code', to: 'website#banking'
  post '/banking/:referral_code', to: 'website#save_banking'
  get  '/app',                    to: 'website#getapp'
  get  '/forgot-password',        to: 'website#forgot_password'
  post '/forgot-password',        to: 'website#forgot_password'
  get  '/reset-password',         to: 'website#reset_password'
  post '/reset-password',         to: 'website#reset_password'
  get '/member-info',             to: 'website#member_information'
  post '/member-info',            to: 'website#member_information'

  # Payfast
  #get  '/transaction/start',   to: 'transactions#payfast'
  #get  '/transaction/cancel',  to: 'transactions#cancel'
  #get  '/transaction/fail',    to: 'transactions#fail'
  #get  '/transaction/success', to: 'transactions#success'

  # Payment Flow
  get '/signup/:referral_code/payment', to: 'signup#payment', as: 'signup_payment'

  scope 'pay_fast' do
    post 'paid'                        => 'payments#complete', as: :payfast_paid
    get  'success'                     => 'payments#success',  as: :payfast_success
    get  'fail'                        => 'payments#fail',     as: :payfast_fail
    get  'cancel/:referral_code'       => 'payments#cancel',   as: :payfast_cancel
    get  'process/:club_id/:member_id' => 'payments#process',  as: :payfast_process
  end

  #--- /Explicit static routing

  get '/recover-account', to: redirect('/forgot-password')

end

app/models/university.rb
class University < ApplicationRecord
  include InstantSearch
  include TableSorting

  use_field_for_search ['name']

  belongs_to :city

  scope :active, -> { where(status: true).order(name: :asc) }
end

app/controllers/admin/universities_controller.rb
class Admin::UniversitiesController < Admin::ApplicationController
  before_action :set_university, only: [:show, :destroy, :edit, :update]
  before_action :set_cities, only: [:new, :edit, :create, :update]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.instant_search(params[:query]).table_sorting(params[:order]).page(params[:page]).per(params[:per_page])
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    render :edit
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit; end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    if @university.save
      redirect_to edit_admin_university_path(@university), notice: 'University was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    if @university.update(university_params)
      redirect_to edit_admin_university_path(@university), notice: 'University was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    redirect_to admin_universities_path, notice: 'University was successfully destroyed.'
  end

  private

  def set_university
    @university = University.find(params[:id])
  end

  def set_cities
    @cities = City.all
  end

  def university_params
    params.require(:university).permit(:id, :name, :status, :city_id, :email_slug)
  end
end

app/controllers/api/v1/universities_controller.rb
class Api::V1::UniversitiesController < Api::V1::BaseController
  ActionController::Parameters.permit_all_parameters = true

  swagger_controller :universities, 'Universities'

  # ----------------------------------------------------------------------------
  # Fetch and display all deals and optionally order them
  # ----------------------------------------------------------------------------
  #
  # GET /api/v1/universities
  #

  swagger_api :index do
    summary 'Returns all University items'
    notes 'This lists all the active universities'
  end

  def index
    @buffer = University.active.as_json(only: [:id, :name, :email_slug, :city_id])
    render json: { universities: @buffer, status: 200 }
  end
end

app/views/admin/universities/_form.html.haml
= simple_form_for [:admin, university], html: { id: 'form-university' } do |f|
  .x_panel
    .x_title
      %h2 University Details
      %ul.nav.navbar-right.panel_toolbox
        %li.right
          %a.collapse-link
            %i.fa.fa-chevron-up
      .clearfix
    .x_content
      - flash.each do |name, msg|
        .alert.alert-success
          = msg
      - if university.errors.any?
        - university.errors.full_messages.each do |e|
          .alert.alert-danger
            = e
      .row
        .col-xs-12
          = f.input :name, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :email_slug, input_html: { class: 'form-control', placeholder: 'Eg. @myuct.ac.za' }
      .row
        .col-xs-12
          = f.input :city_id, as: :select, collection: cities, selected: cities.first.id, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.label :status
          = check_box_tag :false_status, false, true, class: 'cmn-toggle cmn-toggle-round', name: 'university[status]'
          .switch.switch-sm
            = check_box_tag :status, true, university.status, class: 'cmn-toggle cmn-toggle-round', name: 'university[status]'
            %label{ for: 'status' }

app/views/admin/universities/edit.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-shield.page-header-icon
        #{@university.name}
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to admin_universities_path do
          #button-cancel-university.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'university' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', university: @university, cities: @cities

app/views/admin/universities/index.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-university.page-header-icon
        Universities
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to new_admin_university_path, class: 'btn btn-primary btn-lg right' do
          Add University
.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped.jambo_table.bulk_action
        %thead
          %tr.headings
            %th{colspan: '14'}
              .row
                .col-sm-offset-4.col-xs-4.col-sm-3.text-right
                  = render 'admin/dashboards/per_page'
                .col-xs-8.col-sm-5
                  = render 'admin/dashboards/search_form', target: 'universities', query: params[:query], attr: 'name'
          %tr.headings
            %th.column-title
              Name
              = render 'admin/dashboards/column_sorting', model: University, column: :name
            %th.column-title
              Status
              = render 'admin/dashboards/column_sorting', model: University, column: :status
            %th.column-title.no-link.last
              %span.nobr Action
        - if @universities.present?
          %tbody
            - @universities.each do |university|
              %tr.even.pointer
                %td
                  = link_to edit_admin_university_path(university) do
                    = university.name
                %td= university.status ? "Enabled" : "Disabled"
                %td.last{width: '100'}
                  .btn-group
                    = link_to edit_admin_university_path(university), class: 'btn btn-xs btn-default' do
                      %i.fa.fa.fa-pencil
                    = link_to admin_university_path(university), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' do
                      %i.fa.fa-trash
        - else
          %tbody
            %tr.even.pointer
              %td{colspan: '14'}
                No universities to display

= paginate @universities

app/views/admin/universities/new.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-university.page-header-icon
        New University
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to admin_universities_path do
          #button-cancel-university.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'university' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', university: @university, cities: @cities