config/routes.rb
Rails.application.eager_load!

Rails.application.routes.draw do

  devise_for :users

  get '/api', to: redirect('/apidocs/index.html')

  # -- Wixel

  # API
  namespace :api do
    namespace :v1 do
      resources :members, only: [:index] do
        collection do
          post 'login',                action: :login
          post 'signup',               action: :signup
          get  'is_verified',          action: :is_verified
          get  'email_exists',         action: :email_exists
          get  'refer_friends',        action: :refer_friends
          get  'force_verification',   action: :force_verification
          get  'is_paid',              action: :is_paid
          post 'upload_photo',         action: :upload_photo
          get  'profile',              action: :profile
          post 'update_profile',       action: :update_profile
        end
      end
      resources :deals, only: [:index, :show] do
        member do
          get 'toggle_favourite_deal', action: 'toggle_favourite_deal'
        end
      end
      resources :cities,       only: [:index]
      resources :universities, only: [:index]
      resources :invites,      only: [:create]
      # Members
      post 'memberships/activate',         to: 'memberships#activate'
      post 'memberships/otp_check',        to: 'memberships#activate_with_otp'
      post 'memberships/ref_code_check',   to: 'memberships#activate_with_ref_code'
    end
  end

  namespace :admin do
    resources :deals do
      put '/change-status/:status', to: 'deals#toggle_status', constraints: { status: /recommended|online|in_store|published/ }
      member do
        get 'add_branch',    action: 'add_branch'
        get 'remove_branch', action: 'remove_branch'
      end
    end
    resources :merchants do
      resources :branches, only: [:new, :edit]
    end
    resources :branches, except: [:index, :show, :new, :edit]
    resources :cities
    resources :universities
    resources :collections, only: [:index]
    resources :payments
    resources :memberships do
      member do
        get 'payment_details', action: :payment_details
      end
      collection do
        get 'set_as_paid', action: :set_as_paid, as: :bulk_paid
        get 'mail/:mail_request', action: :notify, as: :mail
        match 'report', action: :report, as: :report, via: [:get, :post]
        get 'export/:club_id', action: :export, as: :export
      end
    end
    resources :members, except: [:new] do
      member do
        put 'toggle', action: :toggle_agent
        get 'banking_panel', action: :banking_panel
      end
      collection do
        get '/new/(:id_number)', to: 'members#new', as: :new
      end
    end

    get '/exports', to: 'exports#index', as: 'exports'
    get '/exports/:id/download', to: 'exports#download', as: 'export_download'
    get '/exports/referrals', to: 'exports#referrals', as: 'export_referrals'
    get '/imports', to: 'imports#index', as: 'imports'
    post '/imports', to: 'imports#create'
    get 'imports/sample', to: 'imports#sample', as: 'imports_sample'

    # Reporting
    get 'reports/recon', to: 'reports#recon', as: 'recon_report', :defaults => {:format => :csv}
  end

  # -- /Wixel

  # Handle bank account assignment
  # -- Depreciated -- get 'referralcodes/:referral_code', to: 'memberships#refferalcode', as: 'refferalcode'
  get 'banking_details/signup/:referral_code', to: 'banking_details#new_by_referral', as: 'new_signup_banking_details'
  post 'banking_details/signup/:referral_code', to: 'banking_details#create_by_referral'
  patch 'banking_details/signup/:referral_code', to: 'banking_details#update_by_referral'

  resources :banking_details

  # -- Depreciated --  get 'clubs/:id/members', to: 'clubs#members', as: 'membership_list'
  # -- Depreciated --  get 'clubs/:id/merchants', to: 'clubs#merchants', as: 'club_merchant_list'
  get 'payments/missing', to: 'payments#missing_details', as: 'payment_missing_details'

  # -- Depreciated -- get '/memberships/club/:club_id', to: 'memberships#club', as: 'club_memberships'
  # -- Depreciated -- get '/memberships/member/:member_id', to: 'memberships#member', as: 'member_memberships'

  resources :payments do
    post 'complete' => 'payment#complete', as: 'complete'
    get  'success'  => 'payment#success',  as: 'success'
    get  'fail'     => 'payment#fail',     as: 'fail'
  end

  get 'payments/membership/:membership_id', to: 'payments#process_for_membership', as: 'payment_process_for_membership'

  resources :club_merchants
  resources :locations
  resources :merchants
  resources :members
  resources :memberships
  resources :clubs
  resources :media_contents, only: [:create]

  #get '/cards/:referral_code', to: 'cards#index', as: 'cards'
  get '/admin', to: 'admin/dashboards#index', as: 'admin_home'

  #root to: "signup#index", club_id: 1 #signup_club_path(1) #"admin/clubs#index"

  #get 'signup/club/:club_id',            to: 'signup#index',                  as: 'signup_club'
  #post 'signup/club/:club_id',           to: 'signup#create_signup_club',     as: 'signup_create_club'
  #get 'signup/referral/:referral_code',  to: 'signup#referral',               as: 'signup_referral'
  #post 'signup/referral/:referral_code', to: 'signup#create_signup_referral', as: 'signup_create_referral'
  #post 'invite_friend/:referral_code',   to: 'signup#invite_friend',          as: 'signup_invite_friend'
  #get 'signup/success_test',             to: 'signup#success_page_test',      as: 'signup_success_test'

  root to: "website#index", club_id: 1

  #--- Explicit static routing

  get  '/about',                  to: 'website#about'
  get  '/deals',                  to: 'website#index'
  get  '/welcome',                to: 'website#welcome'
  get  '/recruit',                to: 'website#recruit_earn'
  get  '/join',                   to: 'website#join'
  post '/join',                   to: 'website#do_join'
  get  '/become-a-partner',       to: 'website#become_parter'
  get  '/verify/:referral_code',  to: 'website#verify'
  post  '/verify',                to: 'website#verify'
  get  '/verified',               to: 'website#verified'
  get  '/payment/:referral_code', to: 'website#payment'
  get  '/privacy',                to: 'website#privacy'
  get  '/terms',                  to: 'website#terms'
  get  '/test-mails',             to: 'test#mailers'
  get  '/banking/:referral_code', to: 'website#banking'
  post '/banking/:referral_code', to: 'website#save_banking'
  get  '/app',                    to: 'website#getapp'
  get  '/forgot-password',        to: 'website#forgot_password'
  post '/forgot-password',        to: 'website#forgot_password'
  get  '/reset-password',         to: 'website#reset_password'
  post '/reset-password',         to: 'website#reset_password'
  get '/member-info',             to: 'website#member_information'
  post '/member-info',            to: 'website#member_information'

  # Payfast
  #get  '/transaction/start',   to: 'transactions#payfast'
  #get  '/transaction/cancel',  to: 'transactions#cancel'
  #get  '/transaction/fail',    to: 'transactions#fail'
  #get  '/transaction/success', to: 'transactions#success'

  # Payment Flow
  get '/signup/:referral_code/payment', to: 'signup#payment', as: 'signup_payment'

  scope 'pay_fast' do
    post 'paid'                        => 'payments#complete', as: :payfast_paid
    get  'success'                     => 'payments#success',  as: :payfast_success
    get  'fail'                        => 'payments#fail',     as: :payfast_fail
    get  'cancel/:referral_code'       => 'payments#cancel',   as: :payfast_cancel
    get  'process/:club_id/:member_id' => 'payments#process',  as: :payfast_process
  end

  #--- /Explicit static routing

  get '/recover-account', to: redirect('/forgot-password')

end

app/controllers/admin/memberships_controller.rb
class Admin::MembershipsController < Admin::ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy, :payment_details]
  before_action :set_memberships, only: [:notify, :set_as_paid]
  before_action :set_mail_request, only: [:notify]

  # GET /memberships
  # GET /memberships.json
  def index
    @ms = Membership.join_table.instant_search(params[:query]).filter(params[:filter]).page(params[:page]).per(params[:per_page])
    @memberships = @ms.select_members.table_sorting(params[:order])
  end

  def export
    @memberships = Membership.includes(:club, member: :banking_detail).where(club_id: params[:club_id]).order('created_at DESC')
    respond_to do |format|
      format.csv do
        response.headers['Content-Disposition'] = 'attachment; filename="' + 'memberships-' + Time.now.strftime('%Y-%m-%d_%H:%M:%S') + '.csv"'
        render 'export'
      end
    end
  end

  def report
    respond_to do |format|
      format.html { render 'report' }
      format.csv do
        build_report
        response.headers['Content-Disposition'] = 'attachment; filename="' + 'memberships-report-' + Time.now.strftime('%Y-%m-%d_%H:%M:%S') + '.csv"'
        render 'export'
      end
    end
  end

  def notify
    process_mail_request

    respond_to do |format|
      format.html { redirect_back(fallback_location: admin_home_path) }
      format.json { render json: { status: 'sent' }, status: :ok }
    end
  end

  def set_as_paid
    process_bulk_payment

    respond_to do |format|
      format.html { redirect_back(fallback_location: admin_home_path) }
      format.json { render json: { status: 'completed' }, status: :ok }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show; end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @membership.build_payment
    @membership.member_id = params[:member_id] if params[:member_id]
  end

  # GET /memberships/1/edit
  def edit
    @membership.build_payment unless @membership.payment
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save # and send_signup_mail? and send_referral_mail?
        format.html { redirect_to edit_admin_member_path(@membership.member), notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params) # and send_signup_mail? and send_referral_mail?
        format.html { redirect_to edit_admin_member_path(@membership.member), notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment_details
    @payment = @membership.payment || @membership.build_payment
  end

  private

  def set_membership
    @membership = Membership.includes(:club, :member, :payment).find(params[:id])
    @membership.build_payment unless @membership.payment
  end

  def set_memberships
    @memberships = Membership.includes(:club, :member, :payment).where(id: params[:membership_ids])
  end

  def set_mail_request
    @mail_request = params[:mail_request]
  end

  def process_mail_request
    @memberships.each do |membership|
      case @mail_request
      when 'auto_unpaid'
        send_automated_unpaid_mail membership
      when 'welcome'
        send_signup_mail membership
      when 'payment_reminder'
        send_payment_reminder_mail membership
      when 'banking'
        send_banking_details_mail membership
      when 'referral'
        send_referral_joined_mail membership
      end
    end
  end

  def process_bulk_payment
    @memberships.each do |membership|
      next unless membership.mark_as_paid
      send_signup_mail(membership)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_params
    params.require(:membership).permit(:club_id, :member_id, :status, :referred_by, :paid, :referral_code, :referred_by_code, payment_attributes: [:id, :date_paid, :payment_source, :notes, :reference_number])
  end

  def send_signup_mail(membership)
    MembershipMailer.signup_email(membership.member, membership.club, membership).deliver_later if membership.paid
  end

  def send_payment_reminder_mail(membership)
    MembershipMailer.signup_email(membership.member, membership.club, membership).deliver_later unless membership.paid
  end

  def send_banking_details_mail(membership)
    MembershipMailer.request_banking_details_email(membership).deliver_later if !membership.banking_details? && membership.referrals
  end

  def send_automated_unpaid_mail(membership)
    # MembershipMailer.automated_unpaid_email(membership).deliver_later if membership.id.present? and !membership.paid
    AutomatedUnpaidEmailJob.perform_later(membership)
  end

  def send_referral_joined_mail(membership)
    MembershipMailer.referral_joined_email(membership).deliver_later if membership && !membership.paid
  end

  def build_report
    @report = Membership.new
    @report.search_conditions = params[:search]
    @memberships = @report.report
  end
end

app/controllers/api/v1/memberships_controller.rb
require 'date'

class Api::V1::MembershipsController < Api::V1::BaseController
  before_action :set_agent, only: [:activate, :activate_with_otp, :activate_with_ref_code]

  swagger_controller :memberships, 'Memberships'
  # ----------------------------------------------------------------------------
  # Perform the member sign up request and return its session
  # ----------------------------------------------------------------------------
  #
  # POST /api/v1/memberships/activate
  #
  swagger_api :activate do
    summary 'Send otp'
    notes ''
    param :query, :api_key, :string, false, "agent's api_key"
    param :query, :referral_code, :integer, false, "member's referral code"
    response :success
    response :unauthorized
    response :not_found
  end

  def activate
    @membership = Membership.where(referral_code: params[:referral_code]).where('paid IS null OR paid = false').first
    if @membership
      @member = @membership.member
      @member.update_attribute(:otp, Random.new.rand(1000..9999))
      MemberMailer.otp_email(@member).deliver_now
      render json: { message: 'OTP sent successfully', status: 200 }
    else
      render json: { status: 404, errors: ['Referral code is invalid'] }, status: 404
    end
  end

  # ----------------------------------------------------------------------------
  # Perform account activation using the member OTP
  # ----------------------------------------------------------------------------
  #
  # POST /api/v1/memberships/otp_check
  #
  swagger_api :activate_with_otp do
    summary 'Activate with otp'
    notes ''
    param :query, :api_key, :string, false, "agent's api_key"
    param :query, :otp, :integer, false, "member's otp"
    response :success
    response :unauthorized
    response :not_found
    response :unprocessable_entity
  end

  def activate_with_otp
    @member = Member.find_by_otp(params[:otp]) if params[:otp].present?
    return render json: { status: 401, errors: ['Account with OTP could not be located'] }, status: 401 unless @member && !@member.is_agent
    if @member.membership.activate_by_agent(@agent)
      MemberMailer.otp_complete(@member).deliver_now
      render json: { message: 'Account successfully activated', status: 200 }
    else
      render json: { message: 'Member already activated', status: 422 }, status: 422
    end
  end

  # ----------------------------------------------------------------------------
  # Perform account activation using the referral code
  # ----------------------------------------------------------------------------
  #
  # POST /api/v1/memberships/ref_code_check
  #
  swagger_api :activate_with_ref_code do
    summary 'Activate with referral code'
    notes ''
    param :query, :api_key, :string, false, "agent's api_key"
    param :query, :referral_code, :string, false, "member's referral code"
    response :success
    response :unauthorized
    response :not_found
    response :unprocessable_entity
  end

  def activate_with_ref_code
    @membership = Membership.find_by_referral_code(params[:referral_code])
    return render json: { status: 401, errors: ['Account with referral code could not be located'] }, status: 401 unless @membership
    if @membership.activate_by_agent(@agent)
      render json: { message: 'Account successfully activated', status: 200 }
    else
      render json: { message: 'Member already activated', status: 422 }, status: 422
    end
  end

  private

  def set_agent
    @agent = Member.find_by_api_key(params[:api_key])
    @agent = nil unless @agent.try(:is_agent)
    render json: { status: 404, errors: ['The requester is not a valid agent'] }, status: 404 unless @agent
  end
end

app/views/admin/memberships/_bulk.html.haml
.btn-group
  %button.btn.btn-default{type: 'button' } Bulk Actions
  %button.btn.btn-default.dropdown-toggle{'data-toggle': 'dropdown', type: 'button'}
    %i.fa.fa-caret-down
  %ul.dropdown-menu#bulk-actions
    %li
      = link_to 'Mark as Paid', bulk_paid_admin_memberships_path
    %li.divider
    %li
      = link_to 'Send Payment Reminder', mail_admin_memberships_path(mail_request: 'payment_reminder')
    %li
      = link_to 'Send Welcome', mail_admin_memberships_path(mail_request: 'welcome')
    %li
      = link_to 'Request Banking Details', mail_admin_memberships_path(mail_request: 'banking')
.btn-group
  %button.btn.btn-default{type: 'button'} Filter Memberships
  %button.btn.btn-default.dropdown-toggle{'data-toggle': 'dropdown', type: 'button'}
    %i.fa.fa-caret-down
  %ul.dropdown-menu
    %li
      = link_to 'All', admin_memberships_path(per_page: params[:per_page])
    %li
      = link_to 'Active', admin_memberships_path(filter: 'active', per_page: params[:per_page])
    %li
      = link_to 'Inactive', admin_memberships_path(filter: 'inactive', per_page: params[:per_page])
    %li.divider
    %li
      = link_to 'Paid', admin_memberships_path(filter: 'paid', per_page: params[:per_page])
    %li
      = link_to 'Unpaid', admin_memberships_path(filter: 'unpaid', per_page: params[:per_page])

app/views/admin/memberships/_form.html.haml
#membership-form.modal.fade.membership-details{:role => "dialog", :style => "display: none;", :tabindex => "-1"}
  = simple_form_for([:admin, membership], html: {id: 'form-membership'}) do |f|
    .modal-dialog.modal-sm
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %span.modal-title.valign-middle Membership Details
        .modal-body
          = f.input :member_id, as: :hidden
          .row
            .col-xs-6
              = f.label :status, 'Membership Status'
              = check_box_tag :false_status, false, true, class: 'cmn-toggle cmn-toggle-round', name: 'membership[status]'
              .switch.switch-sm
                = check_box_tag :status, true, membership.status, class: 'cmn-toggle cmn-toggle-round', name: 'membership[status]'
                %label{ for: 'status' }
          .row
            .col-xs-12
              = f.input :referral_code, label: 'Referral Code', input_html: { class: 'form-control', readonly: 'readonly' }
            .col-xs-12
              = f.input :referred_by_code, label: "Referred By #{membership.referred_by_code}", input_html: { class: 'form-control' }
          .row.padding-sm-vr.no-padding-b
            .col-sm-6
              .form-group.no-margin-hr
                %label Paid?
                .switch.switch-sm
                  = check_box_tag :paid, false, false, class: 'cmn-toggle cmn-toggle-round'
                  %label{for: 'paid'}
          #membership-form-payment-details{ style: 'display: none;' }
            =f.fields_for :payment do |p|
              .row
                .col-xs-12
                  = p.input :date_paid, as: :datepicker, label: 'Payment Date', input_html: { class: 'form-control' }
              .row
                .col-xs-12
                  = p.input :payment_source, label: 'Payment Method', as: :select, collection: %w(Cash EFT PayFast), selected: membership.payment.try(:payment_source) || 'Cash', input_html: { class: 'form-control' }
              .row
                .col-xs-12
                  .form-group.no-margin-hr
                    %label.control-label{for: 'referenceno'}
                      Reference#
                      %span.text-light-gray (optional)
                    = p.input :reference_number, label: false, input_html: { class: 'form-control' }
              .row
                .col-xs-12
                  .form-group.no-margin-hr
                    %label.control-label{for: 'paymentnotes'}
                      Notes
                      %span.text-light-gray (optional)
                    = p.input :notes, label: false, input_html: { class: 'form-control' , rows: '3' }
        .modal-footer
          = f.submit 'Save', class: 'btn btn-primary btn-sm'
          %button#btn-cancel-branch.btn.btn-sm.btn-cancel{'data-dismiss': 'modal'} Cancel

app/views/admin/memberships/_membership_table.html.haml
.table-responsive
  %table.table.table-striped.jambo_table.bulk_action.table-1700
    %thead
      %tr.headings
        %th{colspan: '14'}
          .row
            .col-xs-3.col-sm-4
              = render 'admin/memberships/bulk'
            .col-xs-2.col-sm-3.text-right
              = render 'admin/dashboards/per_page'
            .col-xs-7.col-sm-5
              = render 'admin/dashboards/search_form', target: 'memberships', query: params[:query], attr: 'name'
      %tr.headings
        %th
          %input#check-all.flat{:type => "checkbox"}
        %th
          Member
          = render 'admin/dashboards/column_sorting', model: Membership, column: :last_name
        %th
          E-mail
          = render 'admin/dashboards/column_sorting', model: Membership, column: :email
        %th
          Member
          = render 'admin/dashboards/column_sorting', model: Membership, column: :referral_code
        %th
          Student #
          = render 'admin/dashboards/column_sorting', model: Membership, column: :student_email
        %th
          Agent
          = render 'admin/dashboards/column_sorting', model: Membership, column: :is_agent
        %th
          Ref. By
          = render 'admin/dashboards/column_sorting', model: Membership, column: :parent_referral_code
        %th
          Joined
          = render 'admin/dashboards/column_sorting', model: Membership, column: :'members.created_at'
        %th
          Ref. Paid
          = render 'admin/dashboards/column_sorting', model: Membership, column: :paid_members
        %th
          Ref. Unpaid
          = render 'admin/dashboards/column_sorting', model: Membership, column: :unpaid_members
        %th
          Verified
          = render 'admin/dashboards/column_sorting', model: Membership, column: :verified
        %th
          Paid
          = render 'admin/dashboards/column_sorting', model: Membership, column: :paid
        %th
          Bank Details
          = render 'admin/dashboards/column_sorting', model: Membership, column: :bank_name, null_last: true
        %th.no-link.last
          %span.nobr Action
      %tr.headings
        %th.column-title.hidden{colspan: '14'}
        %th.bulk-actions{colspan: '14'}
          %a.antoo
            Bulk Actions (
            %span.action-cnt
            )
            %i.fa.fa-chevron-down
    - if memberships.present?
      %tbody
        - memberships.each do |membership|
          %tr.even.pointer{ 'data-id': membership.member_id }
            %td.a-center
              = check_box_tag :table_records, membership.id, false, class: 'check-item flat'
            %td
              = image_tag membership.member.try(:avatar), class: 'avatar'
              = link_to edit_admin_member_url(membership.member) do
                = membership.member_name
            %td= membership.email
            %td= membership.referral_code
            %td{width: '100'}= membership.member.student_number
            %td
              .switch.switch-sm
                = check_box_tag :agent, true, membership.is_agent, class: 'cmn-toggle cmn-toggle-round switch-agent-status', id: "agent_#{membership.id}"
                %label{ for: "agent_#{membership.id}" }
            %td= membership.parent_referral_code
            %td{width: '100'}
              %i.fa.fa-calendar #{' '}
              = membership.member_created_at.strftime('%Y-%m-%d')
            %td
              .label.label-info= membership.paid_members
            %td
              .label.label-danger= membership.unpaid_members
            %td
              - if membership.verified
                %span.text-success.text-bold Yes
              - else
                %span.text-warning.text-bold No
            %td
              %span
                = link_to payment_details_admin_membership_path(membership), class: "text-bold text-underline #{membership.paid? ? 'text-success' : 'text-warning'}", remote: true do
                  = membership.paid? ? 'Paid' : 'Unpaid'
            %td
              %span
                = link_to banking_panel_admin_member_path(membership.member), class: "text-bold text-underline #{membership.bank_name ? 'text-success' : 'text-warning'}", remote: true do
                  = membership.account_name ? 'Yes' : 'No'
            %td.last{ width: '100' }
              .btn-group
                = link_to edit_admin_member_path(membership.member), class: 'btn btn-xs btn-default' do
                  %i.fa.fa.fa-pencil
                = link_to admin_member_path(membership.member), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' do
                  %i.fa.fa-trash
    - else
      %tbody
        %tr.even.pointer
          %td{colspan: '14'}
            No member to display

app/views/admin/memberships/_new_modal_form.html.haml
.modal.fade#new-member-modal{role: 'dialog', style: 'display: none;', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-hidden': 'true', 'data-dismiss': 'modal', type: 'button'} ×
        %span.modal-title.valign-middle Add new Member
      .modal-body
        %form{action: new_admin_members_path, method: 'get'}
          .row
            .col-sm-12
              .form-group.no-margin-hr
                %label.control-label Student / ID Number *
                %input.form-control{name: 'id_number', type: 'text', value: ''}
                %p.help-block Start with the ID number so we know whether we're creating a member from scratch or updating an existing member's details
          .row
            .col-sm-12
              .form-group.no-margin-hr
                %button.btn.btn-primary.add-new-member Continue
                %a.btn.modal-cancel{'data-dismiss': 'modal', href: '#'} Cancel
                  

app/views/admin/memberships/edit.js.haml
$('#modalForm').empty();
$('#modalForm').html("#{escape_javascript(render 'admin/memberships/form', membership: @membership)}");
$('#membership-form').modal('show');

app/views/admin/memberships/index.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-users.page-header-icon
        Members
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to '#', class: 'btn btn-primary btn-lg right', data: { toggle: 'modal', target: '#new-member-modal' } do
          Add member
.row
  .col-xs-12
    = render 'membership_table', memberships: @memberships

= paginate @ms


#modalForm
= render 'admin/memberships/new_modal_form'

app/views/admin/memberships/report.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-download.page-header-icon
          Membership Reports   
.row
  .col-md-7.col-xs-12
    .x_panel
      .x_title
        %ul.nav.navbar-right.panel_toolbox
          %li.right
            %a.collapse-link
              %i.fa.fa-chevron-up
        .clearfix
      .x_content
        .col-sm-12
          = simple_form_for 'search', url: report_admin_memberships_path(format: 'csv'), method: :post do |f|
            .row
              .col-sm-6
                .form-group.no-margin-hr
                  = f.label :start_date
                  = f.input :start_date, as: :datepicker, label: false, input_html: { placeholder: "dd/mm/yyyy", class: 'form-control' }
              .col-sm-6
                .form-group.no-margin-hr
                  = f.label :end_date
                  = f.input :end_date, as: :datepicker, label: false, input_html: { placeholder: "dd/mm/yyyy", class: 'form-control' }
            .row
              .col-sm-6
                .form-group.no-margin-hr
                  = f.label :location, 'Student Region'
                  = f.input :location, as: :select, collection: study_region_options, selected: 'All', label: false, input_html: { placeholder: "dd/mm/yyyy", class: 'form-control' }
              .col-sm-6
                .form-group.no-margin-hr
                  = f.label :gender
                  = f.input :gender, as: :select, collection: %w(All Female Male), selected: 'All', label: false, input_html: { placeholder: "dd/mm/yyyy", class: 'form-control' }
            .row
              .col-sm-6
                .form-group.no-margin-hr
                  = f.label :status, 'Membership Status'
                  = f.input :status, as: :select, collection: %w(All Paid Unpaid), selected: 'All', label: false, input_html: { placeholder: "dd/mm/yyyy", class: 'form-control' }
            .row
              .col-sm-12
                .form-group.no-margin-hr
                  %button.btn.btn-primary.membership-button-save{type: "submit"} Generate Report