config/routes.rb
Rails.application.eager_load!

Rails.application.routes.draw do

  devise_for :users

  get '/api', to: redirect('/apidocs/index.html')

  # -- Wixel

  # API
  namespace :api do
    namespace :v1 do
      resources :members, only: [:index] do
        collection do
          post 'login',                action: :login
          post 'signup',               action: :signup
          get  'is_verified',          action: :is_verified
          get  'email_exists',         action: :email_exists
          get  'refer_friends',        action: :refer_friends
          get  'force_verification',   action: :force_verification
          get  'is_paid',              action: :is_paid
          post 'upload_photo',         action: :upload_photo
          get  'profile',              action: :profile
          post 'update_profile',       action: :update_profile
        end
      end
      resources :deals, only: [:index, :show] do
        member do
          get 'toggle_favourite_deal', action: 'toggle_favourite_deal'
        end
      end
      resources :cities,       only: [:index]
      resources :universities, only: [:index]
      resources :invites,      only: [:create]
      # Members
      post 'memberships/activate',         to: 'memberships#activate'
      post 'memberships/otp_check',        to: 'memberships#activate_with_otp'
      post 'memberships/ref_code_check',   to: 'memberships#activate_with_ref_code'
    end
  end

  namespace :admin do
    resources :deals do
      put '/change-status/:status', to: 'deals#toggle_status', constraints: { status: /recommended|online|in_store|published/ }
      member do
        get 'add_branch',    action: 'add_branch'
        get 'remove_branch', action: 'remove_branch'
      end
    end
    resources :merchants do
      resources :branches, only: [:new, :edit]
    end
    resources :branches, except: [:index, :show, :new, :edit]
    resources :cities
    resources :universities
    resources :collections, only: [:index]
    resources :payments
    resources :memberships do
      member do
        get 'payment_details', action: :payment_details
      end
      collection do
        get 'set_as_paid', action: :set_as_paid, as: :bulk_paid
        get 'mail/:mail_request', action: :notify, as: :mail
        match 'report', action: :report, as: :report, via: [:get, :post]
        get 'export/:club_id', action: :export, as: :export
      end
    end
    resources :members, except: [:new] do
      member do
        put 'toggle', action: :toggle_agent
        get 'banking_panel', action: :banking_panel
      end
      collection do
        get '/new/(:id_number)', to: 'members#new', as: :new
      end
    end

    get '/exports', to: 'exports#index', as: 'exports'
    get '/exports/:id/download', to: 'exports#download', as: 'export_download'
    get '/exports/referrals', to: 'exports#referrals', as: 'export_referrals'
    get '/imports', to: 'imports#index', as: 'imports'
    post '/imports', to: 'imports#create'
    get 'imports/sample', to: 'imports#sample', as: 'imports_sample'

    # Reporting
    get 'reports/recon', to: 'reports#recon', as: 'recon_report', :defaults => {:format => :csv}
  end

  # -- /Wixel

  # Handle bank account assignment
  # -- Depreciated -- get 'referralcodes/:referral_code', to: 'memberships#refferalcode', as: 'refferalcode'
  get 'banking_details/signup/:referral_code', to: 'banking_details#new_by_referral', as: 'new_signup_banking_details'
  post 'banking_details/signup/:referral_code', to: 'banking_details#create_by_referral'
  patch 'banking_details/signup/:referral_code', to: 'banking_details#update_by_referral'

  resources :banking_details

  # -- Depreciated --  get 'clubs/:id/members', to: 'clubs#members', as: 'membership_list'
  # -- Depreciated --  get 'clubs/:id/merchants', to: 'clubs#merchants', as: 'club_merchant_list'
  get 'payments/missing', to: 'payments#missing_details', as: 'payment_missing_details'

  # -- Depreciated -- get '/memberships/club/:club_id', to: 'memberships#club', as: 'club_memberships'
  # -- Depreciated -- get '/memberships/member/:member_id', to: 'memberships#member', as: 'member_memberships'

  resources :payments do
    post 'complete' => 'payment#complete', as: 'complete'
    get  'success'  => 'payment#success',  as: 'success'
    get  'fail'     => 'payment#fail',     as: 'fail'
  end

  get 'payments/membership/:membership_id', to: 'payments#process_for_membership', as: 'payment_process_for_membership'

  resources :club_merchants
  resources :locations
  resources :merchants
  resources :members
  resources :memberships
  resources :clubs
  resources :media_contents, only: [:create]

  #get '/cards/:referral_code', to: 'cards#index', as: 'cards'
  get '/admin', to: 'admin/dashboards#index', as: 'admin_home'

  #root to: "signup#index", club_id: 1 #signup_club_path(1) #"admin/clubs#index"

  #get 'signup/club/:club_id',            to: 'signup#index',                  as: 'signup_club'
  #post 'signup/club/:club_id',           to: 'signup#create_signup_club',     as: 'signup_create_club'
  #get 'signup/referral/:referral_code',  to: 'signup#referral',               as: 'signup_referral'
  #post 'signup/referral/:referral_code', to: 'signup#create_signup_referral', as: 'signup_create_referral'
  #post 'invite_friend/:referral_code',   to: 'signup#invite_friend',          as: 'signup_invite_friend'
  #get 'signup/success_test',             to: 'signup#success_page_test',      as: 'signup_success_test'

  root to: "website#index", club_id: 1

  #--- Explicit static routing

  get  '/about',                  to: 'website#about'
  get  '/deals',                  to: 'website#index'
  get  '/welcome',                to: 'website#welcome'
  get  '/recruit',                to: 'website#recruit_earn'
  get  '/join',                   to: 'website#join'
  post '/join',                   to: 'website#do_join'
  get  '/become-a-partner',       to: 'website#become_parter'
  get  '/verify/:referral_code',  to: 'website#verify'
  post  '/verify',                to: 'website#verify'
  get  '/verified',               to: 'website#verified'
  get  '/payment/:referral_code', to: 'website#payment'
  get  '/privacy',                to: 'website#privacy'
  get  '/terms',                  to: 'website#terms'
  get  '/test-mails',             to: 'test#mailers'
  get  '/banking/:referral_code', to: 'website#banking'
  post '/banking/:referral_code', to: 'website#save_banking'
  get  '/app',                    to: 'website#getapp'
  get  '/forgot-password',        to: 'website#forgot_password'
  post '/forgot-password',        to: 'website#forgot_password'
  get  '/reset-password',         to: 'website#reset_password'
  post '/reset-password',         to: 'website#reset_password'
  get '/member-info',             to: 'website#member_information'
  post '/member-info',            to: 'website#member_information'

  # Payfast
  #get  '/transaction/start',   to: 'transactions#payfast'
  #get  '/transaction/cancel',  to: 'transactions#cancel'
  #get  '/transaction/fail',    to: 'transactions#fail'
  #get  '/transaction/success', to: 'transactions#success'

  # Payment Flow
  get '/signup/:referral_code/payment', to: 'signup#payment', as: 'signup_payment'

  scope 'pay_fast' do
    post 'paid'                        => 'payments#complete', as: :payfast_paid
    get  'success'                     => 'payments#success',  as: :payfast_success
    get  'fail'                        => 'payments#fail',     as: :payfast_fail
    get  'cancel/:referral_code'       => 'payments#cancel',   as: :payfast_cancel
    get  'process/:club_id/:member_id' => 'payments#process',  as: :payfast_process
  end

  #--- /Explicit static routing

  get '/recover-account', to: redirect('/forgot-password')

end

app/views/layouts/admin/_footer.html.haml
/ footer content
%footer
  .pull-right
    Varsity Vibe
  .clearfix
#custom_notifications.custom-notifications.dsp_none
  %ul.list-unstyled.notifications.clearfix{"data-tabbed_notifications" => "notif-group"}
  .clearfix
  #notif-group.tabbed_notifications

app/views/layouts/admin/_sidenav.html.haml
.col-md-3.left_col
  .left_col.scroll-view
    .navbar.nav_title
      = link_to admin_home_path, class: 'site_title' do
        =image_tag "vvlogo.svg", class: 'site_logo'
        %span Varsity Vibe
    .profile.clearfix
      .profile_pic
        = image_tag 'admin/pixel-admin/avatar-placeholder.png', class: 'img-circle profile_img'
      .profile_info
        %span Welcome,
        %h2 Admin
    %br
    #sidebar-menu.main_menu_side.hidden-print.main_menu
      .menu_section
        %h3 Information
        %ul.nav.side-menu
          %li
            %a
              %i.fa.fa-dashboard
              Dashboard
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'Dashboard', admin_home_path
          %li
            %a
              %i.fa.fa-group
              Members
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Members', admin_memberships_path
          %li
            %a
              %i.fa.fa-money
              Collections
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Collections', admin_collections_path
          %li
            %a
              %i.fa.fa-home
              Cities
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Cities', admin_cities_path
              %li
                = link_to 'Add City', new_admin_city_path
          %li
            %a
              %i.fa.fa-university
              Universities
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Universities', admin_universities_path
              %li
                = link_to 'Add University', new_admin_university_path
          %li
            %a
              %i.fa.fa-briefcase
              Merchants
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Merchants', admin_merchants_path
              %li
                = link_to 'Add Merchant', new_admin_merchant_path
          %li
            %a
              %i.fa.fa-tag
              Deals
              %span.fa.fa-chevron-down
            %ul.nav.child_menu{style: 'display: none'}
              %li
                = link_to 'List Deals', admin_deals_path
              %li
                = link_to 'Add Deal', new_admin_deal_path
      .menu_section
        %h3 Actions
        %ul.nav.side-menu
          %li
            = link_to admin_recon_report_path, data:{ turbolinks: false } do
              %i.fa.fa-download
              Recon Report
    .sidebar-footer.hidden-small
      = link_to destroy_user_session_path, method: :delete do
        %span.glyphicon.glyphicon-off{ 'aria-hidden': 'true' }
      -# %a{'data-placement': 'top', 'data-toggle': 'tooltip', title: 'Logout'}

app/views/layouts/admin/_topnav.html.haml
.top_nav
  .nav_menu
    %nav{ role: 'navigation' }
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.user-profile.dropdown-toggle{'aria-expanded': 'false', 'data-toggle': 'dropdown', href: 'javascript:;'}
            = image_tag 'admin/pixel-admin/avatar-placeholder.png'
            Admin
            %span.fa.fa-angle-down
          %ul.dropdown-menu.dropdown-usermenu.pull-right
            %li
              = link_to destroy_user_session_path, method: :delete do
                %i.fa.fa-sign-out.pull-right
                Log Out

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %meta{charset: 'utf-8'}/
    %meta{content: 'IE=edge,chrome=1', 'http-equiv': 'X-UA-Compatible'}
    %title Varsity Vibe CRM
    %meta{content: 'width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0', name: 'viewport'}
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'admin', 'data-turbolinks-track': true
    = csrf_meta_tags
    / Open Sans font from Google CDN
    %link{href: '//fonts.googleapis.com/css?family=Roboto', rel: 'stylesheet', type: 'text/css'}
    %link{crossorigin: 'anonymous', href: 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', integrity: 'sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==', rel: 'stylesheet'}
%body.nav-md
  .container.body
    .main_container
      -#- flash.each do |key, value|
      -#  #flash{align: 'center', class: 'alert alert-#{key}'}= value
      = render 'layouts/admin/sidenav'
      = render 'layouts/admin/topnav'
      .right_col{ role: 'main' }
        = yield
      -# = render 'layouts/admin/footer'

    = javascript_include_tag 'footermanifest', 'data-turbolinks-track': true