config/routes.rb
Rails.application.eager_load!

Rails.application.routes.draw do

  devise_for :users

  get '/api', to: redirect('/apidocs/index.html')

  # -- Wixel

  # API
  namespace :api do
    namespace :v1 do
      resources :members, only: [:index] do
        collection do
          post 'login',                action: :login
          post 'signup',               action: :signup
          get  'is_verified',          action: :is_verified
          get  'email_exists',         action: :email_exists
          get  'refer_friends',        action: :refer_friends
          get  'force_verification',   action: :force_verification
          get  'is_paid',              action: :is_paid
          post 'upload_photo',         action: :upload_photo
          get  'profile',              action: :profile
          post 'update_profile',       action: :update_profile
        end
      end
      resources :deals, only: [:index, :show] do
        member do
          get 'toggle_favourite_deal', action: 'toggle_favourite_deal'
        end
      end
      resources :cities,       only: [:index]
      resources :universities, only: [:index]
      resources :invites,      only: [:create]
      # Members
      post 'memberships/activate',         to: 'memberships#activate'
      post 'memberships/otp_check',        to: 'memberships#activate_with_otp'
      post 'memberships/ref_code_check',   to: 'memberships#activate_with_ref_code'
    end
  end

  namespace :admin do
    resources :deals do
      put '/change-status/:status', to: 'deals#toggle_status', constraints: { status: /recommended|online|in_store|published/ }
      member do
        get 'add_branch',    action: 'add_branch'
        get 'remove_branch', action: 'remove_branch'
      end
    end
    resources :merchants do
      resources :branches, only: [:new, :edit]
    end
    resources :branches, except: [:index, :show, :new, :edit]
    resources :cities
    resources :universities
    resources :collections, only: [:index]
    resources :payments
    resources :memberships do
      member do
        get 'payment_details', action: :payment_details
      end
      collection do
        get 'set_as_paid', action: :set_as_paid, as: :bulk_paid
        get 'mail/:mail_request', action: :notify, as: :mail
        match 'report', action: :report, as: :report, via: [:get, :post]
        get 'export/:club_id', action: :export, as: :export
      end
    end
    resources :members, except: [:new] do
      member do
        put 'toggle', action: :toggle_agent
        get 'banking_panel', action: :banking_panel
      end
      collection do
        get '/new/(:id_number)', to: 'members#new', as: :new
      end
    end

    get '/exports', to: 'exports#index', as: 'exports'
    get '/exports/:id/download', to: 'exports#download', as: 'export_download'
    get '/exports/referrals', to: 'exports#referrals', as: 'export_referrals'
    get '/imports', to: 'imports#index', as: 'imports'
    post '/imports', to: 'imports#create'
    get 'imports/sample', to: 'imports#sample', as: 'imports_sample'

    # Reporting
    get 'reports/recon', to: 'reports#recon', as: 'recon_report', :defaults => {:format => :csv}
  end

  # -- /Wixel

  # Handle bank account assignment
  # -- Depreciated -- get 'referralcodes/:referral_code', to: 'memberships#refferalcode', as: 'refferalcode'
  get 'banking_details/signup/:referral_code', to: 'banking_details#new_by_referral', as: 'new_signup_banking_details'
  post 'banking_details/signup/:referral_code', to: 'banking_details#create_by_referral'
  patch 'banking_details/signup/:referral_code', to: 'banking_details#update_by_referral'

  resources :banking_details

  # -- Depreciated --  get 'clubs/:id/members', to: 'clubs#members', as: 'membership_list'
  # -- Depreciated --  get 'clubs/:id/merchants', to: 'clubs#merchants', as: 'club_merchant_list'
  get 'payments/missing', to: 'payments#missing_details', as: 'payment_missing_details'

  # -- Depreciated -- get '/memberships/club/:club_id', to: 'memberships#club', as: 'club_memberships'
  # -- Depreciated -- get '/memberships/member/:member_id', to: 'memberships#member', as: 'member_memberships'

  resources :payments do
    post 'complete' => 'payment#complete', as: 'complete'
    get  'success'  => 'payment#success',  as: 'success'
    get  'fail'     => 'payment#fail',     as: 'fail'
  end

  get 'payments/membership/:membership_id', to: 'payments#process_for_membership', as: 'payment_process_for_membership'

  resources :club_merchants
  resources :locations
  resources :merchants
  resources :members
  resources :memberships
  resources :clubs
  resources :media_contents, only: [:create]

  #get '/cards/:referral_code', to: 'cards#index', as: 'cards'
  get '/admin', to: 'admin/dashboards#index', as: 'admin_home'

  #root to: "signup#index", club_id: 1 #signup_club_path(1) #"admin/clubs#index"

  #get 'signup/club/:club_id',            to: 'signup#index',                  as: 'signup_club'
  #post 'signup/club/:club_id',           to: 'signup#create_signup_club',     as: 'signup_create_club'
  #get 'signup/referral/:referral_code',  to: 'signup#referral',               as: 'signup_referral'
  #post 'signup/referral/:referral_code', to: 'signup#create_signup_referral', as: 'signup_create_referral'
  #post 'invite_friend/:referral_code',   to: 'signup#invite_friend',          as: 'signup_invite_friend'
  #get 'signup/success_test',             to: 'signup#success_page_test',      as: 'signup_success_test'

  root to: "website#index", club_id: 1

  #--- Explicit static routing

  get  '/about',                  to: 'website#about'
  get  '/deals',                  to: 'website#index'
  get  '/welcome',                to: 'website#welcome'
  get  '/recruit',                to: 'website#recruit_earn'
  get  '/join',                   to: 'website#join'
  post '/join',                   to: 'website#do_join'
  get  '/become-a-partner',       to: 'website#become_parter'
  get  '/verify/:referral_code',  to: 'website#verify'
  post  '/verify',                to: 'website#verify'
  get  '/verified',               to: 'website#verified'
  get  '/payment/:referral_code', to: 'website#payment'
  get  '/privacy',                to: 'website#privacy'
  get  '/terms',                  to: 'website#terms'
  get  '/test-mails',             to: 'test#mailers'
  get  '/banking/:referral_code', to: 'website#banking'
  post '/banking/:referral_code', to: 'website#save_banking'
  get  '/app',                    to: 'website#getapp'
  get  '/forgot-password',        to: 'website#forgot_password'
  post '/forgot-password',        to: 'website#forgot_password'
  get  '/reset-password',         to: 'website#reset_password'
  post '/reset-password',         to: 'website#reset_password'
  get '/member-info',             to: 'website#member_information'
  post '/member-info',            to: 'website#member_information'

  # Payfast
  #get  '/transaction/start',   to: 'transactions#payfast'
  #get  '/transaction/cancel',  to: 'transactions#cancel'
  #get  '/transaction/fail',    to: 'transactions#fail'
  #get  '/transaction/success', to: 'transactions#success'

  # Payment Flow
  get '/signup/:referral_code/payment', to: 'signup#payment', as: 'signup_payment'

  scope 'pay_fast' do
    post 'paid'                        => 'payments#complete', as: :payfast_paid
    get  'success'                     => 'payments#success',  as: :payfast_success
    get  'fail'                        => 'payments#fail',     as: :payfast_fail
    get  'cancel/:referral_code'       => 'payments#cancel',   as: :payfast_cancel
    get  'process/:club_id/:member_id' => 'payments#process',  as: :payfast_process
  end

  #--- /Explicit static routing

  get '/recover-account', to: redirect('/forgot-password')

end

app/models/merchant.rb
class Merchant < ApplicationRecord
  include InstantSearch
  include TableSorting

  use_field_for_search %w(name merchant_type phone email)

  has_many :locations, inverse_of: :merchant
  has_many :branches, dependent: :destroy
  has_many :club_merchants
  has_many :clubs, through: :club_merchants
  has_many :deals

  mount_uploader :logo, MerchantUploader
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]
  before_action :set_default_branch, only: [:edit]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.instant_search(params[:query]).table_sorting(params[:order]).page(params[:page]).per(params[:per_page])
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = 'attachment; filename=\"merchants-info.csv\"'
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    redirect_to edit_admin_merchant_path(@merchant)
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    if @merchant.save
      redirect_to edit_admin_merchant_path(@merchant), notice: 'Merchant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to admin_merchant_url(@merchant), notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    redirect_to admin_merchants_url, notice: 'Merchant was successfully destroyed.'
  end

  private

  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  def set_default_branch
    @branch = @merchant.branches.new
  end

  def merchant_params
    params.require(:merchant).permit(:name, :merchant_type, :deal_description, :logo, :discount, :phone, :email, :url, :operating_hours, :terms, :how_to_redeem)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
  def clear_str(str)
    str.delete(',').gsub('&quot', '').split(/[\r\t\n]/).join('')
  end
end

app/views/admin/merchants/_branches.html.haml
.x_panel
  .x_title
    %h2 Branches
    %ul.nav.navbar-right.panel_toolbox
      %li.right
        %a.collapse-link
          %i.fa.fa-chevron-up
    .clearfix
  .x_content
    %table.table.table-hover
      %thead
        %tr
          %td Name
          %td City
          %td.text-right Action
      %tbody
        - merchant.branches.each do |branch|
          %tr
            %td
              = link_to edit_admin_merchant_branch_path(merchant, branch), remote: true do
                = branch.name
            %td= branch.city.try(:name)
            %td.last.text-right{width: '100'}
              .btn-group
                = link_to edit_admin_merchant_branch_path(merchant, branch), remote: true, class: 'btn btn-default btn-xs' do
                  %i.fa.fa.fa-pencil
                = link_to admin_branch_path(branch), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do
                  %i.fa.fa-times
    = link_to 'Add Branch', new_admin_merchant_branch_path(merchant), class: 'btn btn-primary btn-sm right', remote: true

app/views/admin/merchants/_form.html.haml
= simple_form_for [:admin, merchant], html: { id: 'form-merchant' } do |f|
  = f.input :enabled, as: :hidden, input_html: { value: true }
  .x_panel
    .x_title
      %h2 Merchant Details
      %ul.nav.navbar-right.panel_toolbox
        %li.right
          %a.collapse-link
            %i.fa.fa-chevron-up
      .clearfix
    .x_content
      - flash.each do |name, msg|
        .alert.alert-success
          = msg
      - if merchant.errors.any?
        - merchant.errors.full_messages.each do |e|
          .alert.alert-danger
            = e
      .row
        .col-xs-12
          = f.input :name, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :deal_description, label: 'Slogan/Blurb', input_html: { class: 'form-control' }
      .row
        .col-xs-12.col-sm-6
          = f.input :phone, input_html: { class: 'form-control' }
        .col-xs-12.col-sm-6
          = f.input :email, input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :url, label: 'URL', input_html: { class: 'form-control' }
          .alert.alert-info
            %button.close{'data-dismiss': 'alert', type: 'button'} &#xD7;
            %strong Heads up!
            Remember to add
            %strong http://
            to all URL's
      .row
        .col-xs-12
          = f.input :merchant_type, label: 'Type', input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :terms, label: 'Terms & Conditions', input_html: { class: 'form-control' }
      .row
        .col-xs-12
          = f.input :how_to_redeem, label: 'How to Redeem In Store', input_html: { class: 'form-control' }
  .x_panel
    .x_title
      %h2 Merchant Logo
      %ul.nav.navbar-right.panel_toolbox
        %li.right
          %a.collapse-link
            %i.fa.fa-chevron-up
      .clearfix
    .x_content
      .row
        .col-sm-12.text-center.input
          = image_tag merchant.logo
        .col-sm-12
          = f.input :logo, label: 'Logo (450x450 - png or jpg)', accept: 'image/png,image/jpeg'

app/views/admin/merchants/edit.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        #{@merchant.name}
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to admin_merchants_path do
          #button-cancel-merchant.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'merchant' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', merchant: @merchant
  .col-xs-12.col-md-5
    = render 'branches', merchant: @merchant

#modalForm
%script{:src => "//maps.google.com/maps/api/js?lsensor=false&libraries=geometry&anguage=en&key=AIzaSyD3s9MZciVozRJbIj2-r52_H1a3DFw6EFY"}
%script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
%script{:src => "//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js", :type => "text/javascript"}

app/views/admin/merchants/index.csv.erb
<%- headers = ['Name',
               'Slogan',
               'Phone',
               'Email',
               'URL',
               'Type',
               'T&Cs',
               'Name',
               'City',
               'Email',
               'Phone',
               'Address',
               'Longtitude',
               'Latitude',
               'Title',
               'Recomende',
               'Online?',
               'Instore?',
               'Published?',
               'Expration',
               'Blurb',
               'Deal Details',
               'Notes',
               'T&Cs',
               'URL',
               'Twitter',
               'Facebook',
               'Instagram',
               'Pinterest',
               'SEO Focus Keywords',
               'SEO Description',
               'Ordeing Weight'] -%>
<%- blank_merchant = Array.new(7){ |index| " "} -%>
<%- blank_branch = Array.new(7){ |index| " "} -%>
<%- blank_deal = Array.new(18){ |index| " "} -%>

<%= CSV.generate_line headers %>
<%- @merchants.each_with_index do |merchant, m_index| -%>
    <%- merchant_line = [clear_str(merchant.name),
                         merchant.deal_description? ? clear_str(merchant.deal_description) : 'Unknown',
                         merchant.phone? ? clear_str(merchant.phone) : 'Unknown',
                         merchant.email? ? clear_str(merchant.email) : 'Unknown',
                         merchant.url? ? clear_str(merchant.url) : 'Unknown',
                         merchant.merchant_type? ? clear_str(merchant.merchant_type) : 'Unknown',
                         merchant.terms? ? clear_str(merchant.terms) : 'Unknown']  -%>
    <% @branches = merchant.branches -%>
    <%- @branches.each_with_index do |branch, b_index| -%>
        <%- branch_line = [clear_str(branch.name),
                           clear_str(branch.city_name),
                           branch.email? ? clear_str(branch.email) : 'Unknown',
                           clear_str(branch.phone),
                           clear_str(branch.address),
                           branch.lng.to_s,
                           branch.lat.to_s] -%>
        <%- @deals = branch.deals -%>
        <%- if @deals.count == 0 -%>
            <%- line = (b_index == 0 ? merchant_line : blank_merchant) + branch_line + blank_deal -%>
            <%= CSV.generate_line(line) %>
        <%- else -%>
            <%- @deals.each_with_index do |deal, d_index| -%>
                <%- deal_line = [clear_str(deal.title),
                                 deal.recommended,
                                 deal.online,
                                 deal.in_store,
                                 deal.published,
                                 deal.premium,
                                 deal.blurb? ? clear_str(deal.blurb) : 'Unknown',
                                 deal.deal? ? clear_str(deal.deal) : 'Unknown',
                                 deal.note? ? clear_str(deal.note) : 'Unknown',
                                 deal.terms? ? clear_str(deal.terms) : 'Unknown',
                                 deal.url? ? deal.url : 'Unknown',
                                 deal.twitter? ? deal.twitter : 'Unknown',
                                 deal.facebook? ? deal.facebook : 'Unknown',
                                 deal.instagram? ? deal.instagram : 'Unknown',
                                 deal.pinterest? ? deal.pinterest : 'Unknown',
                                 deal.seo_keyword? ? clear_str(deal.seo_keyword) : 'Unknown',
                                 deal.seo_description? ? clear_str(deal.seo_description) : 'Unknown',
                                 deal.ordering,] -%>
                <%- line = (b_index == 0 && d_index == 0 ? merchant_line : blank_merchant) + (d_index == 0 ? branch_line : blank_branch) + deal_line -%>
                <%= CSV.generate_line(line) %>
            <%- end -%>
        <%- end -%>
    <%- end -%>
<%- end -%>

app/views/admin/merchants/index.html.haml
.page-header.border-t
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        Merchants
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to admin_merchants_path(:csv), class: 'btn btn-default  btn-lg' do
          Download Merchants
        = link_to new_admin_merchant_path, class: 'btn btn-primary  btn-lg' do
          Add Merchant
.row
  .col-sm-12
    .table-responsive
      %table.table.table-striped.jambo_table.bulk_action
        %thead
          %tr.headings
            %th{colspan: '14'}
              .row
                .col-sm-offset-4.col-xs-4.col-sm-3.text-right
                  = render 'admin/dashboards/per_page'
                .col-xs-8.col-sm-5
                  = render 'admin/dashboards/search_form', target: 'merchants', query: params[:query], attr: 'name'
          %tr.headings
            %th.column-title
              Merchant
              = render 'admin/dashboards/column_sorting', model: Merchant, column: :name
            %th.column-title
              Type
              = render 'admin/dashboards/column_sorting', model: Merchant, column: :merchant_type
            %th.column-title
              Phone
              = render 'admin/dashboards/column_sorting', model: Merchant, column: :phone
            %th.column-title
              Email
              = render 'admin/dashboards/column_sorting', model: Merchant, column: :email
            %th.column-title.no-link.last
              %span.nobr Action
        - if @merchants.present?
          %tbody
            - @merchants.each do |merchant|
              %tr
                %td.a-center
                  = link_to edit_admin_merchant_path(merchant) do
                    = merchant.name
                %td= merchant.merchant_type || 'Unknown'
                %td= merchant.phone? ? merchant.phone : 'Unknown'
                %td.a-right.a-right= merchant.email || 'Unknown'
                %td.last{width: '100'}
                  .btn-group
                    = link_to edit_admin_merchant_path(merchant), class: 'btn btn-xs btn-default' do
                      %i.fa.fa.fa-pencil
                    = link_to admin_merchant_path(merchant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' do
                      %i.fa.fa-trash
        - else
          %tbody
            %tr.even.pointer
              %td{colspan: '14'}
                No merchants to display

= paginate @merchants

app/views/admin/merchants/new.html.haml
.page-header
  .row
    .col-xs-6.col-sm-6
      %h1
        %i.fa.fa-briefcase.page-header-icon
        New Merchant
    .col-xs-6.col-sm-6.text-right
      %h1
        = link_to admin_merchants_path do
          #button-cancel-merchant.btn.btn-lg.btn-cancel
            Cancel
        %button.submit-form-button.btn.btn-primary.btn-lg{ 'data-target': 'merchant' } Save
.row
  .col-xs-12.col-md-7
    = render 'form', merchant: @merchant

app/views/admin/merchants/show.html.haml
%p#notice= notice
asdasd
%p
  %strong Name:
  = @merchant.name
%p
  %strong Merchant type:
  = @merchant.merchant_type
%p
  %strong Deal description:
  = @merchant.deal_description
%p
  %strong Logo:
  = @merchant.logo
%p
  %strong Discount:
  = @merchant.discount
%p
  %strong Phone:
  = @merchant.phone
%p
  %strong Email:
  = @merchant.email
%p
  %strong Operating hours:
  = @merchant.operating_hours
= link_to 'Edit', edit_merchant_path(@merchant)
|
= link_to 'Back', merchants_path